name: Download new database version
on: workflow_dispatch

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install AWS CLI
        run: sudo apt-get install awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.OBJECT_STORE_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.OBJECT_STORE_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Download data.db from Cloudflare R2
        run: |
          aws --endpoint-url=${{ secrets.OBJECT_STORE_ENDPOINT }} s3 cp s3://your-bucket-name/data.db data.db

      - name: Commit update
        run: |
          git config --global user.name 'Corentin Smith'
          git config --global user.email 'cosmith@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/cosmith/cosmith.fr

          git checkout "${GITHUB_REF:11}"
          git add data.db
          git commit -m "[Automated] Updated data.db from object store"
          git push
